package entity;

public enum Status {
    EXAM_CREATED,
    CLASH,
    OTHER,
    PROCTOR_INVALID,
    PROCTOR_UNAVAILABLE,
    STUDENT_ADDED,
    REGISTRATION_NUMBER_INVALID,
    PROCTOR_AVAILABLE
}
